"""Add indexes for performance

Revision ID: 0457ae5e10cb
Revises: bb237f753e73
Create Date: 2026-04-11 02:39:59.450164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0457ae5e10cb'
down_revision = 'bb237f753e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_profile_username'), ['username'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('public_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_profile_username'))

    # ### end Alembic commands ###
