"""add revenue_events table

Revision ID: a987932bf3d9
Revises: 202604111201
Create Date: 2026-04-11 23:37:09.623602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a987932bf3d9'
down_revision = '202604111201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('einnahme_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Float(), nullable=False),
    sa.Column('waehrung', sa.String(length=16), nullable=False),
    sa.Column('typ', sa.String(length=32), nullable=False),
    sa.Column('quelle', sa.String(length=128), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('estimated_revenue', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('diamonds', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    op.drop_table('revenue_events')
    op.drop_table('einnahme_info')
    # ### end Alembic commands ###
