"""add oauth tokens

Revision ID: ff0e989c5f5b
Revises: a3c42268e6f4
Create Date: 2026-04-12 04:34:53.465748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0e989c5f5b'
down_revision = 'a3c42268e6f4'
branch_labels = None
depends_on = None


def upgrade():
    # Prüfe, ob die Tabelle bereits existiert
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'oauth_tokens' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('oauth_tokens',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('provider', sa.String(length=32), nullable=False),
            sa.Column('access_token_enc', sa.Text(), nullable=False),
            sa.Column('refresh_token_enc', sa.Text(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=True),
            sa.Column('scope', sa.Text(), nullable=True),
            sa.Column('token_type', sa.String(length=32), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_token_user_provider')
        )
        with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_oauth_tokens_provider'), ['provider'], unique=False)
            batch_op.create_index(batch_op.f('ix_oauth_tokens_user_id'), ['user_id'], unique=False)
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_provider'))

    op.drop_table('oauth_tokens')
    # ### end Alembic commands ###
